server/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path('nginx/auth_request/', views.NginxAuthRequestView.as_view(),
         name="nginx_auth_request"),

    # manage users
    path('users/', views.UsersView.as_view(),
         name="users"),
    path('users/invite/', views.InviteUserView.as_view(),
         name="invite_user"),
    path('users/create_service_account/', views.CreateServiceAccountView.as_view(),
         name="create_service_account"),
    path('users/<int:pk>/', views.UserView.as_view(),
         name="user"),
    path('users/<int:pk>/update/', views.UpdateUserView.as_view(),
         name="update_user"),
    path('users/<int:pk>/delete/', views.DeleteUserView.as_view(),
         name="delete_user"),

    # manage users API tokens
    path('users/<int:user_pk>/api_tokens/create/', views.CreateUserAPITokenView.as_view(),
         name="create_user_api_token"),
    path('users/<int:user_pk>/api_tokens/<uuid:pk>/update/', views.UpdateUserAPITokenView.as_view(),
         name="update_user_api_token"),
    path('users/<int:user_pk>/api_tokens/<uuid:pk>/delete/', views.DeleteUserAPITokenView.as_view(),
         name="delete_user_api_token"),

    # manage users OIDC API token issuers
    path('users/<int:user_pk>/api_token_issuers/oidc/create/',
         views.CreateOIDCAPITokenIssuerView.as_view(),
         name="create_oidc_api_token_issuer"),
    path('users/<int:user_pk>/api_token_issuers/oidc/<uuid:pk>/',
         views.OIDCAPITokenIssuerView.as_view(),
         name="oidc_api_token_issuer"),
    path('users/<int:user_pk>/api_token_issuers/oidc/<uuid:pk>/update/',
         views.UpdateOIDCAPITokenIssuerView.as_view(),
         name="update_oidc_api_token_issuer"),
    path('users/<int:user_pk>/api_token_issuers/oidc/<uuid:pk>/delete/',
         views.DeleteOIDCAPITokenIssuerView.as_view(),
         name="delete_oidc_api_token_issuer"),

    # manage tasks
    path('tasks/', views.TasksView.as_view(),
         name="tasks"),
    path('tasks/<uuid:task_id>/', views.TaskView.as_view(),
         name="task"),

    # manage groups
    path('roles/', views.GroupsView.as_view(), name="groups"),
    path('roles/create/', views.CreateGroupView.as_view(), name="create_group"),
    path('roles/<int:pk>/', views.GroupView.as_view(), name="group"),
    path('roles/<int:pk>/update/', views.UpdateGroupView.as_view(), name="update_group"),
    path('roles/<int:pk>/delete/', views.DeleteGroupView.as_view(), name="delete_group"),

    # user views
    path('settings/profile/', views.ProfileView.as_view(), name="profile"),
    path('settings/profile/update/', views.UpdateProfileView.as_view(), name="update_profile"),
    path('settings/verification_devices/', views.UserVerificationDevicesView.as_view(),
         name="verification_devices"),
    path('settings/verification_devices/add_totp/', views.AddTOTPView.as_view(),
         name="add_totp"),
    path('settings/verification_devices/totp/<int:pk>/delete/', views.DeleteTOTPView.as_view(),
         name="delete_totp"),
    path('verify_totp/', views.VerifyTOTPView.as_view(),
         name='verify_totp'),
    path('settings/verification_devices/register_webauthn_device/', views.RegisterWebAuthnDeviceView.as_view(),
         name="register_webauthn_device"),
    path('settings/verification_devices/webauthn/<int:pk>/delete/', views.DeleteWebAuthnDeviceView.as_view(),
         name="delete_webauthn_device"),
    path(r'verify_webauthn/', views.VerifyWebAuthnView.as_view(),
         name='verify_webauthn'),
]

server/base/urls.py
from django.urls import re_path
from . import views


app_name = "base"
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^health_check/$', views.HealthCheckView.as_view(), name='health_check'),
    re_path(r'^app/(?P<app>\S+)/hist_data/(?P<interval>\S+)/(?P<bucket_number>\d+)/$',
            views.AppHistogramDataView.as_view(), name='app_hist_data'),
]

server/realms/urls.py
from django.urls import path
from . import views


app_name = "realms"
urlpatterns = [
    # index
    path('', views.IndexView.as_view(), name='index'),

    # users
    path('users/', views.RealmUserListView.as_view(), name='users'),
    path('users/<uuid:pk>/', views.RealmUserView.as_view(), name='user'),
    path('users/<uuid:pk>/groups/add/', views.AddRealmUserToGroupView.as_view(),
         name='add_user_to_group'),
    path('users/<uuid:pk>/groups/<uuid:group_pk>/remove/', views.RemoveRealmUserFromGroupView.as_view(),
         name='remove_user_from_group'),

    # groups
    path('groups/', views.RealmGroupListView.as_view(), name='groups'),
    path('groups/create/', views.CreateRealmGroupView.as_view(), name='create_group'),
    path('groups/<uuid:pk>/', views.RealmGroupView.as_view(), name='group'),
    path('groups/<uuid:pk>/update/', views.UpdateRealmGroupView.as_view(), name='update_group'),
    path('groups/<uuid:pk>/delete/', views.DeleteRealmGroupView.as_view(), name='delete_group'),

    # realm group mappings
    path('group_mappings/',
         views.RealmGroupMappingListView.as_view(),
         name='realm_group_mappings'),
    path('group_mappings/create/',
         views.CreateRealmGroupMappingView.as_view(),
         name='create_realm_group_mapping'),
    path('group_mappings/<uuid:pk>/update/',
         views.UpdateRealmGroupMappingView.as_view(),
         name='update_realm_group_mapping'),
    path('group_mappings/<uuid:pk>/delete/',
         views.DeleteRealmGroupMappingView.as_view(),
         name='delete_realm_group_mapping'),

    # role mappings
    path('role_mappings/',
         views.RoleMappingListView.as_view(),
         name='role_mappings'),
    path('role_mappings/create/',
         views.CreateRoleMappingView.as_view(),
         name='create_role_mapping'),
    path('role_mappings/<uuid:pk>/update/',
         views.UpdateRoleMappingView.as_view(),
         name='update_role_mapping'),
    path('role_mappings/<uuid:pk>/delete/',
         views.DeleteRoleMappingView.as_view(),
         name='delete_role_mapping'),

    # realms
    path('realms/', views.RealmListView.as_view(), name='list'),
    path('realms/<slug:backend>/create/', views.CreateRealmView.as_view(), name='create'),
    path('realms/<uuid:pk>/', views.RealmView.as_view(), name='view'),
    path('realms/<uuid:pk>/update/', views.UpdateRealmView.as_view(), name='update'),

    # SSO test views
    path('realms/<uuid:pk>/test/', views.TestRealmView.as_view(), name='test'),
    path('realms/<uuid:pk>/sessions/<uuid:ras_pk>/', views.RealmAuthenticationSessionView.as_view(),
         name='authentication_session'),
]

server/server/urls.py
import logging
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from accounts.views import login
from accounts.forms import PasswordResetForm
from zentral.conf import settings as zentral_settings
from zentral.utils.views import server_error

logger = logging.getLogger(__name__)

# base
urlpatterns = [
    path('', include('base.urls')),
    path('api/', include('base.api_urls')),
    path('metrics/', include('base.metrics_urls')),

    # OpenAPI schema endpoints
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    # special login view with verification device redirect
    path('accounts/login/', login, name='login'),

    # add all the auth urls except the login
    path('accounts/logout/', auth_views.LogoutView.as_view(),
         name='logout'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(form_class=PasswordResetForm),
         name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


# zentral apps
def build_urlpatterns_for_zentral_apps():
    """ Builds urlpatterns objects from zentral app configurations.

    Returns:
        urlpatterns: a list of path or re_path elements
    """
    urlpatterns = []
    for app_name, app_config in zentral_settings.get('apps', {}).items():
        app_shortname = app_name.rsplit('.', 1)[-1]
        for url_prefix, url_module_name in (("", "urls"),
                                            ("api/", "api_urls"),
                                            ("metrics/", "metrics_urls"),
                                            ("public/", "public_urls")):
            if url_module_name == "metrics_urls" and not app_config.get("metrics", False):
                continue
            try:
                urlpatterns.append(path(f"{url_prefix}{app_shortname}/", include(f"{app_name}.{url_module_name}")))
                if (url_module_name == "public_urls" and app_config.get('mount_legacy_public_endpoints', False)):
                    urlpatterns.append(
                        path(
                            f"{app_shortname}/",
                            include(
                                f"{app_name}.{url_module_name}",
                                namespace=f"{app_shortname}_public_legacy"
                            )
                        )
                    )
            except ModuleNotFoundError:
                pass
    return urlpatterns


urlpatterns.extend(build_urlpatterns_for_zentral_apps())

# static files
urlpatterns += staticfiles_urlpatterns()

# JSON 500 errors if possible
handler500 = server_error

server/base/views.py
import logging
from django.apps import apps
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse, JsonResponse
from django.views.generic import TemplateView, View
from zentral.core.stores.conf import stores


logger = logging.getLogger("server.base.views")


class HealthCheckView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('OK')


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "base/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        app_list = []
        for app_name, app_config in apps.app_configs.items():
            if not self.request.user.has_module_perms(app_name):
                continue
            events_module = getattr(app_config, "events_module", None)
            if not events_module:
                continue
            if getattr(events_module, "ALL_EVENTS_SEARCH_DICT", None):
                app_list.append(app_name)
        app_list.sort()
        context["apps"] = app_list
        return context


class AppHistogramDataView(LoginRequiredMixin, View):
    INTERVAL_DATE_FORMAT = {
        "hour": "%H:%M",
        "day": "%d/%m",
        "week": "%d/%m",
        "month": "%m/%y",
    }

    def get(self, request, *args, **kwargs):
        app = kwargs['app']
        try:
            zentral_app = apps.app_configs[app]
            search_dict = getattr(zentral_app.events_module, "ALL_EVENTS_SEARCH_DICT")
        except (KeyError, AttributeError):
            raise Http404
        if set(search_dict.keys()) != {"tag"} or not isinstance(search_dict["tag"], str):
            logger.error("Incompatible app %s all event search dict", app)
            raise Http404
        if not self.request.user.has_module_perms(app):
            raise PermissionDenied("Not allowed")
        interval = kwargs["interval"]
        bucket_number = int(kwargs["bucket_number"])
        app_tag = search_dict["tag"]
        try:
            date_format = self.INTERVAL_DATE_FORMAT[interval]
        except KeyError:
            raise Http404
        labels = []
        event_count_data = []
        unique_msn_data = []
        for dt, event_count, unique_msn in stores.admin_console_store.get_app_hist_data(
            interval, bucket_number, app_tag
        ):
            labels.append(dt.strftime(date_format))
            event_count_data.append(event_count)
            unique_msn_data.append(unique_msn)
        datasets = {"event_count": {
                        "label": "{} events".format(app),
                        "backgroundColor": "rgb(122, 199, 189, 0.7)",
                        "data": event_count_data
                    },
                    "unique_msn": {
                        "label": "{} machines".format(app),
                        "backgroundColor": "rgb(234, 81, 101, 0.7)",
                        "data": unique_msn_data
                    }}
        return JsonResponse({"app": app,
                             "labels": labels,
                             "datasets": datasets})

server/templates/_button.html
{% if url %}
<a href="{{ url }}" type="button" class="btn btn-link{% if classes %} {{ classes }}{% endif %}"{% if tooltip %} data-bs-toggle="tooltip" data-bs-placement="{{ placement }}" data-bs-title="{{ tooltip }}"{% endif %}>
  <i class="{{ icon }}"></i>
</a>
{% endif %}

server/templates/_created_updated_at.html
<div class="table-responsive">
    <table class="table w-auto">
        <tbody>
        {% if object.provisioning_uid %}
            <tr>
                <th class="border-0 p-0 pe-3 text-secondary">Provisioning UID</th>
                <td class="border-0 p-0 text-secondary">{{ object.provisioning_uid }}</td>
            </tr>
        {% endif %}
        {% if object.version %}
            <tr>
                <th class="border-0 p-0 pe-3 text-secondary">Version</th>
                <td class="border-0 p-0 text-secondary">{{ object.version }}</td>
            </tr>
        {% endif %}
        <tr>
            <th class="border-0 p-0 pe-3 text-secondary">Created at</th>
            <td class="border-0 p-0 text-secondary">{{ object.created_at|date:'r' }}</td>
        </tr>
        <tr>
            <th class="border-0 p-0 pe-3 text-secondary">Updated at</th>
            <td class="border-0 p-0 text-secondary">{{ object.updated_at|date:'r' }}</td>
        </tr>
        {% if object.archived_at %}
        <tr>
            <th class="border-0 p-0 pe-3 text-secondary">Archived at</th>
            <td class="border-0 p-0 text-secondary">{{ object.archived_at|date:'r' }}</td>
        </tr>
        {% endif %}
    </tbody></table>
</div>

server/templates/_empty_results.html
<div class="text-center py-5">
    <p><i class="bi bi-emoji-frown"></i></p>
    <h5>We didn't find any item related to your search</h5>
    {% if reset_search_link %}
    <h6>Why don't you see <a href="{{ reset_search_link }}">all the items</a>?</h6>
    {% endif %}
</div>

server/templates/_modules_menu.html
{% for section in section_list %}
    <div class="d-flex justify-content-start">
        <a class="list-group-item list-group-item-action rounded m-1 p-1 w-100 px-2"
            data-bs-toggle="collapse"
            href="#offcanvas{{ section.title|cut:" " }}Submenu"
            role="button"
            aria-expanded="{% if section.is_active %}false{% else %}true{% endif %}"
            aria-controls="offcanvas{{ section.title|cut:" " }}Submenu">
            {{ section.title }}
            <i class="collapse-toggler float-end{% if not section.is_active %} collapsed{% endif %}"
                data-bs-toggle="collapse"
                aria-expanded="{% if section.is_active %}false{% else %}true{% endif %}"
                data-bs-target="#offcanvas{{ section.title|cut:" " }}Submenu" 
                ></i>
        </a>
    </div>
    <div class="collapse{%if section.is_active %} show{% endif %}" id="offcanvas{{ section.title|cut:" " }}Submenu">
        <div class="list-group rounded-0 small">
                {% for link, anchor_text, active in section.link_list %}
                <div class="d-flex justify-content-start px-2">
                    <a class="list-group-item list-group-item-action rounded m-1 p-1 w-auto px-2 ms-2{%if active %} active{% endif %}" href="{{ link }}">{{ anchor_text }}</a>
                </div>
                {% endfor %}
        </div>
    </div>
{% endfor %}

server/templates/_no_entities.html
<div class="text-center py-5">
    <h5>There are no {{ entity_name }} created.</h5>
    {% if create_new_entity_link %}
        <h6>Why don't you <a href="{{ create_new_entity_link }}">create one</a>?</h6>
    {% endif %}
</div>

server/templates/_pagination.html
{% if next_url or previous_url %}
    <nav aria-label="Page navigation">
        <ul class="pagination pagination-sm d-flex justify-content-end">
            <li class="page-item {% if not previous_url %}disabled{% endif %}">
                <a class="page-link" href="{{ previous_url }}"><i class="bi bi-caret-left"></i> Previous</a>
            </li>
            <li class="page-item {% if not next_url %}disabled{% endif %}">
                <a class="page-link" href="{{ next_url }}">Next <i class="bi bi-caret-right"></i></a>
            </li>
        </ul>
    </nav>
{% endif %}

server/templates/base.html
{% load static base_extras %}
<!doctype html>
<html lang="en" class="d-flex flex-column h-100" data-bs-theme="light">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Zentral</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link href="{% static 'dist/main.css' %}" rel="stylesheet">
    <script src="{% static 'dist/theme.js' %}"></script>
</head>
<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg sticky-top">
        <div class="d-flex flex-row flex-wrap w-100 align-items-center px-3">
            <a class="navbar-brand" href="/">
                <i class="zentral-logo" alt="Zentral"></i>
            </a>
            <div class="ms-auto">
                <div class="user-menu">
                  {% include "user_menu.html" %}
                </div>
                {% if user.is_authenticated %}
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>
                {% else %}
                <ul class="nav">
                  {% include "toggle_theme.html" with placement_class="dropdown-menu-end"%}
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="d-flex h-100 overflow-auto">
        {% if user.is_authenticated %}
        <div class="offcanvas offcanvas-start sidebar sticky-lg-top flex-lg-shrink-0 d-flex flex-column" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header d-lg-none">
                <div class="offcanvas-title" id="offcanvasNavbarLabel">
                    {% include "user_menu.html" %}
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>

            <div class="list-group rounded-0 border-0 overflow-auto px-2">

                {% pinned_menu %}

                <hr>

                {% modules_menu %}

            </div>
            {% if request.zentral_deployment.items_for_display %}
            <div class="deployment-info">
                {% for k, v in request.zentral_deployment.items_for_display %}
                    {{ k }}: {{ v }}
                    {% if not forloop.last %}
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

        </div>
        {% endif %}
        <main class="container-fluid overflow-auto">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
        </main>
    </div>
    <script src="{% static 'dist/main.js' %}"></script>
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script nonce="{{ request.csp_nonce }}">
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
      });
    </script>
    {% block extrajs %}
    {% endblock %}
  </body>
</html>

server/templates/base_error.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zentral</title>
  <link rel="shortcut icon" href="{% if fqdn %}https://{{ fqdn }}{% endif %}{% static 'favicon.ico' %}">
  <link href="{% if fqdn %}https://{{ fqdn }}{% endif %}{% static 'dist/main.css' %}" rel="stylesheet">
  <script src="{% if fqdn %}https://{{ fqdn }}{% endif %}{% static 'dist/theme.js' %}"></script>
</head>
  <body class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% if fqdn %}https://{{ fqdn }}{% endif %}">
        <i class="zentral-logo" alt="Zentral"></i>
      </a>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

server/templates/custom_error_page.html
{% extends 'base_error.html' %}

{% block content %}
<p class="display-1">{{ status_code }}</p>
<p class="fs-3">{{ message }}</p>
{% endblock %}

server/templates/toggle_theme.html
<li class="nav-item dropdown">
    <button id="bd-theme" type="button" class="nav-link btn btn-link" href="#" role="button" aria-expanded="false"  data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme">
        <i class="bi bi-moon-stars" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Toggle theme"></i>
    </button>
    <ul class="dropdown-menu {{ placement_class }}" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" id="bd-theme-dark" class="dropdown-item bi bi-moon" aria-pressed="true" data-bs-theme-value="dark"> Dark Mode</button>
        </li>
        <li>
            <button type="button" id="bd-theme-light" class="dropdown-item bi bi-sun" aria-pressed="true" data-bs-theme-value="light"> Light Mode</button>
        <li>
            <button type="button" id="bd-theme-auto" class="dropdown-item bi bi-circle-half" aria-pressed="true" data-bs-theme-value="auto"> Auto</button>
        </li>
    </ul>
</li>

server/templates/user_menu.html
{% load base_extras incidents_extras %}

<ul class="nav z-3">
    {% if user.is_authenticated %}
    {% include "toggle_theme.html" with placement_class="dropdown-menu-lg-end"%}
    {% if zentral_extra_links %}
    <li class="nav-item dropdown">
        <a class="nav-link btn btn-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-display" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Extra links"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
            {% for link in zentral_extra_links %}
                <li>
                    <a class="dropdown-item" href="{{ link.url }}" target="_blank">
                        {{ link.anchor_text }}
                        <span class="bi bi-box-arrow-up-right"></span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </li>
    {% endif %}
    {% if perms.incidents.view_incident %}
        <li class="nav-item dropdown">
            <a class="nav-link btn btn-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-exclamation-triangle" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Major Open Incidents"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end px-2" style="width: auto;">
                {% get_latest_open_incidents as open_incidents %}
                {% if open_incidents %}
                    {% for incident in open_incidents %}
                        <li class="text-nowrap"><a class="dropdown-item" href="{{ incident.get_absolute_url }}">{% incident_severity incident.severity %} {{ incident.name }}</a></li>
                    {% endfor %}
                {% else %}
                    <li class="text-nowrap">No Open Incidents 🎉</li>
                {% endif %}
            </ul>
        </li>
    {% endif %}
    <li class="nav-item dropdown">
        <a class="nav-link btn btn-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots-vertical" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Platform settings"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
            {% if perms.accounts.view_user %}
            <li><a class="dropdown-item" href="{% url 'accounts:users' %}">Users</a></li>
            {% endif %}
            {% if perms.accounts.view_group %}
            <li><a class="dropdown-item" href="{% url 'accounts:groups' %}">Roles</a></li>
            {% endif %}
            {% if perms.realms.view_realm %}
            <li><a class="dropdown-item" href="{% url 'realms:list' %}">Realms</a></li>
            {% endif %}
            {% if perms.realms.view_realmgroup %}
            <li><a class="dropdown-item" href="{% url 'realms:groups' %}">Realm Groups</a></li>
            {% endif %}
            {% if perms.probes.view_action %}
            <li><a class="dropdown-item" href="{% url 'probes:actions' %}">Actions</a></li>
            {% endif %}
            {% if perms.stores.view_store %}
            <li><a class="dropdown-item" href="{% url 'stores:index' %}">Stores</a></li>
            {% endif %}
            {% if perms.terraform.view_state %}
            <li><a class="dropdown-item" href="{% url 'terraform:index' %}">Terraform</a></li>
            {% endif %}
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link btn btn-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="User settings"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
            {% if not request.realm_authentication_session.is_remote %}
            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:verification_devices' %}">Verification Devices</a></li>
            {% else %}
            <li style="padding:3px 20px"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> {{ request.realm_authentication_session.realm }}</li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'accounts:tasks' %}">Tasks</a></li>
            <li role="separator" class="dropdown-divider"></li>
            <li><form id="logout-form" action="{% url 'logout' %}" method="POST">{% csrf_token %}<button type="submit" class="dropdown-item">Sign Out</button></form></li>
        </ul>
    </li>
    {% endif %}
</ul>