zentral/core/incidents/urls.py
from django.urls import path
from . import views

app_name = "incidents"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.IncidentView.as_view(), name='incident'),
    path('<int:pk>/update/', views.UpdateIncidentView.as_view(), name='update_incident'),
    path('<int:incident_pk>/machine_incident/<int:pk>/update/',
         views.UpdateMachineIncidentView.as_view(), name='update_machine_incident'),

    # events
    path('<int:pk>/events/',
         views.IncidentEventsView.as_view(), name='incident_events'),
    path('<int:pk>/events/fetch/',
         views.FetchIncidentEventsView.as_view(), name='fetch_incident_events'),
    path('<int:pk>/events/store_redirect/',
         views.IncidentEventsStoreRedirectView.as_view(), name='incident_events_store_redirect'),
]

pinned_menu_cfg = {
    'weight': 2,
    'items': (
        ('index', 'all incidents', False, ("incidents.view_incident",)),
    ),
}

zentral/core/incidents/models.py
from enum import Enum
import logging
from typing import NamedTuple
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.functional import cached_property
from . import incident_class_from_type


logger = logging.getLogger('zentral.core.incidents.models')


class Severity(Enum):
    CRITICAL = 300
    MAJOR = 200
    MINOR = 100
    NONE = 0

    def __str__(self):
        return self.name.title()

    @classmethod
    def choices(cls, include_none=False):
        return tuple((i.value, str(i)) for i in cls if i != cls.NONE or include_none)


class Status(Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"

    def __str__(self):
        return self.name.replace("_", " ").title()

    @classmethod
    def choices(cls):
        return tuple((i.value, str(i)) for i in cls)

    @classmethod
    def open_values(cls):
        return {cls.OPEN.value, cls.IN_PROGRESS.value, cls.REOPENED.value}

    @classmethod
    def closed_values(cls):
        return {cls.CLOSED.value, cls.RESOLVED.value}

    def next_statuses(self):
        if self == Status.OPEN or self == Status.REOPENED:
            return [Status.IN_PROGRESS, Status.CLOSED, Status.RESOLVED]
        elif self == Status.IN_PROGRESS:
            return [Status.CLOSED, Status.RESOLVED]
        elif self == Status.CLOSED or self == Status.RESOLVED:
            return [Status.REOPENED]


class IncidentUpdate(NamedTuple):
    incident_type: str
    key: dict
    severity: Severity

    @classmethod
    def deserialize(cls, incident_update_d):
        return cls(
            incident_type=incident_update_d["incident_type"],
            key=incident_update_d["key"],
            severity=Severity(incident_update_d["severity"])
        )

    def serialize(self):
        d = self._asdict()
        d["severity"] = d["severity"].value
        return d


class Incident(models.Model):
    incident_type = models.CharField(max_length=256)
    key = models.JSONField()
    severity = models.PositiveIntegerField(choices=Severity.choices())
    name = models.TextField()
    status = models.CharField(max_length=64, choices=Status.choices())
    status_time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name="one_open_incident_per_incident_type_and_key",
                fields=["incident_type", "key"],
                condition=Q(status__in=Status.open_values())
            ),
        ]
        indexes = [
            models.Index(fields=["incident_type", "key"]),
        ]
        ordering = ("-created_at",)

    def get_absolute_url(self):
        return reverse("incidents:incident", args=(self.pk,))

    def serialize_for_event(self):
        return {
            "pk": self.pk,
            "type": self.incident_type,
            "key": self.key,
            "severity": self.severity,
            "status": self.status,
            "status_time": self.status_time
        }

    def get_next_statuses(self):
        next_statuses = Status(self.status).next_statuses()
        if self.machineincident_set.filter(status__in=Status.open_values()).count():
            for status in (Status.CLOSED, Status.RESOLVED):
                try:
                    next_statuses.remove(status)
                except ValueError:
                    pass
        if Status.REOPENED in next_statuses:
            if Incident.objects.filter(
                incident_type=self.incident_type,
                key=self.key,
                status__in=Status.open_values()
            ).exists():
                next_statuses.remove(Status.REOPENED)
        return next_statuses

    def get_next_status_choices(self):
        return [(s.value, str(s)) for s in self.get_next_statuses()]

    @cached_property
    def loaded_incident(self):
        cls = incident_class_from_type(self.incident_type)
        return cls(self)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.name = self.loaded_incident.get_name()
        return super().save(*args, **kwargs)

    def get_open(self, latest):
        """ Returns the latest Incidents with
            Status OPEN ordered by severity DESC and created time DESC

        Args:
            latest (int): the 'latest' amount of incidents created.
        """
        return Incident.objects.all().filter(
            status=Status.OPEN.value,
            ).order_by("-severity").order_by("-created_at")[:latest]


class MachineIncident(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE)
    serial_number = models.TextField(db_index=True)
    status = models.CharField(max_length=64, choices=Status.choices())
    status_time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(
                name="one_open_machine_incident_per_incident",
                fields=["incident", "serial_number"],
                condition=Q(status__in=Status.open_values())
            )
        ]

    def get_absolute_url(self):
        return "{}#{}".format(reverse("incidents:incident", args=(self.incident.pk,)), self.pk)

    def serialize_for_event(self):
        d = self.incident.serialize_for_event()
        d["machine_incident"] = {
            "pk": self.pk,
            "status": self.status,
            "status_time": self.status_time
        }
        return d

    def get_next_statuses(self):
        return Status(self.status).next_statuses()

    def get_next_status_choices(self):
        return [(s.value, str(s)) for s in self.get_next_statuses()]

zentral/core/incidents/templates/incidents/incident_detail.html
{% extends 'base.html' %}
{% load base_extras incidents_extras inventory_extras ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'incidents:index' %}">Incidents</a>
  {% if reset_link %}
  <li class="breadcrumb-item"><a href="{{ reset_link }}">{{ object.name }}</a></li>
  {% else %}
  <li class="breadcrumb-item active">{{ object.name }}</li>
  {% endif %}
  {% if perms.incidents.view_machineincident and paginator.count and paginator.num_pages > 1 %}
  <li class="breadcrumb-item active">page {{ page.number }} of {{ paginator.num_pages }}</li>
  {% endif %}
</ol>


<div class="object-details">
    <div class="d-flex align-items-center mb-1">
        <h2 class="m-0">{{ incident.name }}</h2>
        <div class="ms-3">
            {% if show_events_link %}
                {% url 'incidents:incident_events' object.pk as url %}
                {% button 'EVENTS' url %}
            {% endif %}
            {% for link, anchor_text in store_links %}
                {% button 'LINK' link anchor_text %}
            {% endfor %}
        </div>
    </div>

    <div class="d-flex align-items-center mb-3">
        <h3 class="m-0 fs-5 text-secondary">Incident</h3>
        <div class="ms-auto">
            {% if perms.incidents.change_incident and object.get_next_statuses %}
                {% url 'incidents:update_incident' object.pk as url %}
                {% button 'UPDATE' url "Edit Status" %}
            {% endif %}
        </div>
    </div>

    <table class="table-object-properties">
    <tbody>
        <tr>
        <td style="width:20vw">Severity</td>
        <td>{% incident_severity incident.severity %}</td>
        </tr>
        <tr>
        <td>Status</td>
        <td>{{ incident.get_status_display }}</td>
        </tr>
        {% for section, objects in objects %}
        <tr>
        <td>{{ section }}</td>
        <td>
            <ul class="list-unstyled">
            {% for link, obj in objects %}
            <li>
                {% if link %}
                <a href="{{ link }}">{{ obj }}</a>
                {% else %}
                {{ obj }}
                {% endif %}
            </li>
            {% endfor %}
            </ul>
        </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    {% created_updated_at object %}

</div>


{% if perms.incidents.view_machineincident and paginator.count %}
<h3>Machine incident{{ paginator.count|pluralize }} ({{ paginator.count }})</h3>

{% pagination next_url previous_url %}

<table class="table table-striped align-middle table-hover">
  <thead>
    <th>Serial number</th>
    <th>Status</th>
    <th>Created at</th>
    <th>Updated at</th>
    {% if perms.incidents.change_machineincident %}
    <th></th>
    {% endif %}
  </thead>
  <tbody>
    {% for machine_incident in machine_incidents %}
    <tr class="data-row">
      <td id="{{ machine_incident.pk }}">
        {% if perms.inventory.view_machinesnapshot %}
        <a href="{% machine_url machine_incident.serial_number %}">{{ machine_incident.serial_number|privacywrapper }}</a>
        {% else %}
        {{ machine_incident.serial_number|privacywrapper }}
        {% endif %}
      </td>
      <td>{{ machine_incident.get_status_display }}</td>
      <td>{{ machine_incident.created_at }}</td>
      <td>{{ machine_incident.updated_at }}</td>
      {% if perms.incidents.change_machineincident %}
      <td class="text-end py-0">
        {% url 'incidents:update_machine_incident' object.pk machine_incident.pk as url %}
        {% button 'UPDATE' url "Edit Status" %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>

{% pagination next_url previous_url %}

{% endif %}

{% endblock %}

zentral/core/incidents/templates/incidents/incident_events.html
{% extends 'base.html' %}
{% load base_extras inventory_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'incidents:index' %}">Incidents</a></li>
  <li class="breadcrumb-item"><a href="{% url 'incidents:incident' incident.pk %}">{{ incident.name }}</a></li>
  <li class="breadcrumb-item active">Events</li>
</ol>

<div class="sticky-top bg-body z-1">
  <h3>
    {{ incident.name }} - events
  </h3>
  {% include "core/stores/events_form.html" %}
</div>

{% include "core/stores/events_table.html" %}

{% endblock %}

{% block extrajs %}
{% include "core/stores/events_script.html" %}
{% endblock %}

zentral/core/incidents/templates/incidents/incident_form.html
{% extends 'base.html' %}
{% load incidents_extras inventory_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'incidents:index' %}">Incidents</a>
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></li>
  <li class="breadcrumb-item active">update</li>
</ol>

<h2>{{ incident.name }}</h2>
<h3>Update machine incident status</h3>
<p>{% incident_severity incident.severity %}</p>
<dl class="row">
  <dt class="col-sm-3 text-md-end">Current status</dt>
  <dd class="col-sm-9">{{ object.get_status_display }}</dd>
  <dt class="col-sm-3 text-md-end">Created at</dt>
  <dd class="col-sm-9">{{ object.created_at }}</dd>
  <dt class="col-sm-3 text-md-end">Updated at</dt>
  <dd class="col-sm-9">{{ object.updated_at }}</dd>
</dl>

<form method="post" class="update-form">{% csrf_token %}

    {{ form }}

    <p>
        <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">
            Cancel
        </a>
        <button class="btn btn-primary" type="submit">
            Update
        </button>
    </p>
</form>
{% endblock %}

zentral/core/incidents/templates/incidents/index.html
{% extends 'base.html' %}
{% load ui_extras incidents_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  {% for url, anchor_text in breadcrumbs %}
  {% if url %}
  <li class="breadcrumb-item"><a href="{{ url }}">{{ anchor_text }}</a>
  {% else %}
  <li class="breadcrumb-item active">{{ anchor_text }}</li>
  {% endif %}
  {% endfor %}
</ol>

<div class="d-flex justify-content-between mb-3">
    <h2 class="m-0">Incident{{ paginator.count|pluralize }} ({{ paginator.count }})</h2>
</div>

<div class="d-flex flex-wrap align-items-center mb-1">
    <form method="GET" class="search-form">

        {{ form }}

        <button type="submit" class="btn btn-link mb-2">
            <i class="bi bi-search"></i>
        </button>
    </form>
</div>

{% if object_list %}
    {% pagination next_url previous_url %}

    <div class="table-responsive mb-3">
        <table class="table table-striped align-middle table-hover">
            <thead>
            <th>Name</th>
            <th>Status</th>
            <th>Severity</th>
            <th>Created at</th>
            </thead>
            <tbody>
            {% for incident in object_list %}
            <tr>
            <td><a href="{{ incident.get_absolute_url }}">{{ incident.name }}</a></td>
            <td>{{ incident.get_status_display }}</td>
            <td>{% incident_severity incident.severity %}</td>
            <td>{{ incident.created_at }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% pagination next_url previous_url %}
{% elif form.has_changed %}
    {% url 'incidents:index' as empty_results_url %}
    {% empty_results empty_results_url %}
{% endif %}

{% endblock %}

zentral/core/incidents/templates/incidents/machineincident_form.html
{% extends 'base.html' %}
{% load base_extras incidents_extras inventory_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'incidents:index' %}">Incidents</a>
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ incident.name }}</a></li>
  <li class="breadcrumb-item active">{{ object.serial_number|privacywrapper }}</li>
  <li class="breadcrumb-item active">update</li>
</ol>

<h2>Incident <em>{{ incident.name }}</em></h2>
<h3>Update machine incident status</h3>
<p>{% incident_severity incident.severity %}</p>
<dl class="row">
  <dt class="col-sm-3 text-md-end">Machine</dt>
  <dd class="col-sm-9"><a href="{% machine_url object.serial_number %}">{{ object.serial_number|privacywrapper }}</a></dd>
  <dt class="col-sm-3 text-md-end">Current status</dt>
  <dd class="col-sm-9">{{ object.get_status_display }}</dd>
  <dt class="col-sm-3 text-md-end">Created at</dt>
  <dd class="col-sm-9">{{ object.created_at }}</dd>
  <dt class="col-sm-3 text-md-end">Updated at</dt>
  <dd class="col-sm-9">{{ object.updated_at }}</dd>
</dl>

<form method="post" class="update-form">{% csrf_token %}
  
    {{ form }}
  
    <p>
        <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">
        Cancel
        </a>
        <button class="btn btn-primary" type="submit">
        Update
        </button>
    </p>
</form>
{% endblock %}