zentral/contrib/google_workspace/urls.py
from django.urls import path
from . import views

app_name = "google_workspace"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('connections/', views.ConnectionsView.as_view(), name="connections"),
    path('connections/create/', views.CreateConnectionView.as_view(), name="create_connection"),
    path('connections/redirect/', views.ConnectionRedirectView.as_view(), name="redirect"),
    path('connections/<uuid:pk>/', views.ConnectionView.as_view(), name="connection"),
    path('connections/<uuid:pk>/authorize/', views.AuthorizeConnectionView.as_view(), name="authorize_connection"),
    path('connections/<uuid:pk>/update/', views.UpdateConnectionView.as_view(), name="update_connection"),
    path('connections/<uuid:pk>/delete/', views.DeleteConnectionView.as_view(), name="delete_connection"),
    path('connections/<uuid:conn_pk>/group_tag_mappings/create/',
         views.CreateGroupTagMappingView.as_view(), name="create_group_tag_mapping"),
    path('connections/<uuid:conn_pk>/group_tag_mappings/<uuid:pk>/update/',
         views.UpdateGroupTagMappingView.as_view(), name="update_group_tag_mapping"),
    path('connections/<uuid:conn_pk>/group_tag_mappings/<uuid:pk>/delete/',
         views.DeleteGroupTagMappingView.as_view(), name="delete_group_tag_mapping"),
]

modules_menu_cfg = {
    'items': (
        ('index', 'Overview', False, ('google_workspace',)),
        ('connections', 'Connections', False, ('google_workspace.view_connection',)),
    ),
    'weight': 70,
}

zentral/contrib/google_workspace/models.py
import hashlib
import logging
import uuid
from django.db import models
from django.urls import reverse
from zentral.contrib.inventory.models import Tag
from zentral.core.secret_engines import decrypt_str, encrypt_str, rewrap
from django.utils.translation import gettext_lazy as _


logger = logging.getLogger("zentral.contrib.google_worspace.models")


class ConnectionManager(models.Manager):
    def can_be_deleted(self):
        return self.filter(
            ~models.Exists(GroupTagMapping.objects.filter(connection=models.OuterRef("pk"))),
        )


class Connection(models.Model):
    class Type(models.TextChoices):
        OAUTH_ADMIN_SDK = "OAUTH", _("OAuth Admin SDK"),
        SERVICE_ACCOUNT_CLOUD_IDENTITY = "SA_CLOUD_ID", _("Service Account Could Identity")

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(unique=True)
    client_config = models.TextField(editable=False)
    user_info = models.TextField(null=True, editable=False)
    customer_id = models.CharField(blank=True, null=True)
    type = models.CharField(choices=Type, default=Type.OAUTH_ADMIN_SDK)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("google_workspace:connection", args=(self.pk,))

    # secrets

    def _get_secret_engine_kwargs(self, field):
        return {
            "model": "google_workspace.connection",
            "pk": str(self.pk),
            "field": field,
        }

    def get_client_config(self):
        if not self.client_config:
            return
        return decrypt_str(self.client_config, **self._get_secret_engine_kwargs("client_config"))

    def set_client_config(self, client_config):
        self.client_config = encrypt_str(client_config, **self._get_secret_engine_kwargs("client_config"))

    def get_user_info(self):
        if not self.user_info:
            return
        return decrypt_str(self.user_info, **self._get_secret_engine_kwargs("user_info"))

    def set_user_info(self, user_info):
        if user_info is None:
            self.user_info = None
            return
        self.user_info = encrypt_str(user_info, **self._get_secret_engine_kwargs("user_info"))

    def rewrap_secrets(self):
        self.client_config = rewrap(self.client_config, **self._get_secret_engine_kwargs("client_config"))
        self.user_info = rewrap(self.user_info, **self._get_secret_engine_kwargs("user_info"))

    def serialize_for_event(self, keys_only=False):
        d = {"pk": str(self.pk), "name": self.name}
        if keys_only:
            return d
        match self.type:
            case Connection.Type.OAUTH_ADMIN_SDK:
                d.update({"client_config_hash": hashlib.sha256(self.get_client_config().encode("utf-8")).hexdigest()})
            case Connection.Type.SERVICE_ACCOUNT_CLOUD_IDENTITY:
                d.update({"customer_id": self.customer_id})
        d.update({
            "type": self.type,
            "created_at": self.created_at,
            "updated_at": self.updated_at
            })
        return d

    def can_be_deleted(self):
        return Connection.objects.can_be_deleted().filter(pk=self.pk).exists()

    objects = ConnectionManager()


class GroupTagMapping(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    connection = models.ForeignKey(Connection, on_delete=models.CASCADE)
    group_email = models.EmailField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (("connection", "group_email"),)

    def get_absolute_url(self):
        return reverse("google_workspace:connection", args=(self.connection.pk,)) + f"#gtm-{self.pk}"

    def serialize_for_event(self, keys_only=False):
        d = {"pk": str(self.pk), "group_email": self.group_email}
        if keys_only:
            return d
        d.update({
            "connection": self.connection.serialize_for_event(keys_only=True),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "tags": [tag.serialize_for_event(keys_only=True) for tag in self.tags.all().order_by("name")]
            })
        return d

zentral/contrib/google_workspace/templates/google_workspace/connection_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:connections" %}">Connections</a></li>
  <li class="breadcrumb-item active">Remove connection</li>
</ol>

<h2>Remove connection</h2>

<form method="post" class="update-form">{% csrf_token %}
  <p>Do you really want to remove connection <i>{{ object }}</i>?</p>
  <p>
    <a class="btn btn-outline-secondary" href="{{ object.get_absolute_url }}">Cancel</a>
    <button class="btn btn-danger" type="submit">Remove</button>
  </p>
</form>
{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/connection_detail.html
{% extends 'base.html' %}
{% load base_extras %}
{% load ui_extras %}
{% load inventory_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:connections" %}">Connections</a></li>
  <li class="breadcrumb-item active"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
</ol>

<div class="object-details">
    <div class="d-flex align-items-center mb-1">
      <h2 class="m-0">{{ object }}</h2>
    </div>
    <div class="d-flex align-items-center mb-3">
        <h3 class="m-0 fs-5 text-secondary">Connection</h3>
        <div class="ms-auto">
            {% if perms.google_workspace.change_connection and not connection_authorized %}
            <a href="{% url 'google_workspace:authorize_connection' object.pk %}" class="btn btn-link"
                data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Authorize">
                <i class="bi bi-arrow-left-right"></i>
            </a>
            {% endif %}
        </div>
    </div>

    
    <div class="table-responsive mb-3">
      <table class="table-object-properties">
        <thead>
          <th width="width:30vw">Attribute</th>
          <th>Value</th>
        </thead>
        <tbody>
        <tr>
          <td>Type</td>
          <td>{{ object.get_type_display }}</td>
        </tr>
        {% if object.type == "SA_CLOUD_ID" %}
        <tr>
          <td>Customer ID</td>
          <td>{{ object.customer_id }}</td>
        </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
    
    
    <div class="table-responsive mb-3">
        {% if connection_authorized %}
        <table class="table-object-properties">
        <thead>
            {% if api_client.credentials %}
            <tr>
            <th style="width:30vw">Scope</th>
            </tr>
            {% endif %}
        </thead>
        <tbody>
            {% if api_client.credentials %}
                {% for scope in api_client.credentials.scopes %} 
            <tr><td>{{scope}}</td></tr>
                {%endfor%}
            {% endif %}
        </tbody>
        </table>
        {% else %}
        <div>Authorization needed for {{ object }} connection</div>
        {% endif %}

        {% created_updated_at object %}

    </div>
</div>

<div class="d-flex justify-content-between mb-3">
    <h3 class="m-0" id="grouptagmappings">Group tag mapping{{ group_tag_mappings_count|pluralize }} ({{ group_tag_mappings_count }})</h3>
    <div class="ms-auto">
    {% if perms.google_workspace.add_grouptagmapping and connection_authorized %}
        {% url 'google_workspace:create_group_tag_mapping' object.id as url %}
        {% button 'CREATE' url "Create new group tag mapping" %}
    {% endif %}
    {% if perms.google_workspace.change_grouptagmapping and connection_authorized %}
        <a id="grouptagmappings-sync-btn" href="{% url 'google_workspace_api:sync_tags' object.id %}"
            class="btn btn-link task" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Synchronize">
                <i class="bi bi-arrow-repeat"></i>
        </a>
    {% endif %}
     </div>
</div>

{% if group_tag_mappings_count %}
<div class="table-responsive mb-3">
    <table class="table table-striped align-middle table-hover">
    <thead>
        <th>Name</th>
        <th>Tags</th>
        {% if perms.google_workspace.change_grouptagmapping or perms.google_workspace.delete_grouptagmapping %}
        <th></th>
        {% endif %}
    </thead>
    <tbody>
        {% for group_tag_mapping in group_tag_mappings %}
        <tr id="gtm-{{ group_tag_mapping.pk }}" class="data-row">
        <td>{{ group_tag_mapping.group_email }}</td>
        <td>
            {% for tag in group_tag_mapping.tags.all %}
                {% inventory_tag tag %}
                {% empty %}
                -
            {% endfor %}
        </td>
        {% if perms.google_workspace.change_grouptagmapping or perms.google_workspace.delete_grouptagmapping %}

        <td xclass="text-end py-0">
            {% if connection_authorized %}
                {% if perms.google_workspace.change_grouptagmapping %}
                    {% url 'google_workspace:update_group_tag_mapping' object.id group_tag_mapping.pk as url %}
                    {% button 'UPDATE' url "Edit group tag mapping" %}
                {% endif %}
                {% if perms.google_workspace.delete_grouptagmapping %}
                    {% url 'google_workspace:delete_group_tag_mapping' object.id group_tag_mapping.pk as url %}
                    {% button 'DELETE' url "Delete group tag mapping" %}
                {% endif %}
            {% endif %}
        </td>
        {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endif %}

{% endblock %}

{% block extrajs %}
<script nonce="{{ request.csp_nonce }}">
  var WAIT_FOR_TASK_TIMEOUT_ID;

  function waitForTask(url) {
    $.ajax({
      dataType: "json",
      url: url,
      success: function (data) {
        if (data.unready) {
          WAIT_FOR_TASK_TIMEOUT_ID = window.setTimeout(waitForTask, 1000, url);
        } else {
          $("#grouptagmappings-sync-btn").prop("disabled", false);
          if (data.status === "SUCCESS") {
            window.location.reload();
          }
        }
      }
    });
  }

  function launchTask($link) {
      $link.prop("disabled", true);
      var url = $link.attr("href");
      $.ajax({
        dataType: "json",
        url: url,
        method: "post",
        success: function (data) {
            
          WAIT_FOR_TASK_TIMEOUT_ID = window.setTimeout(waitForTask, 300, data.task_result_url);
        }
      });
  }

  $(document).ready(function () {
    $(".task").click(function (event) {
      event.preventDefault();
      launchTask($(this));
    });
  });
</script>
{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/connection_form.html
{% extends 'base.html' %}
{% load base_extras %}
{% load ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:connections" %}">Connections</a></li>
  {% if object %}
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="breadcrumb-item active">Update</li>
  {% else %}
  <li class="breadcrumb-item active">Create</li>
  {% endif %}
</ol>

<h2>{% if object %}Update {{object}}{% else %}Create connection{% endif %}</h2>

<form class="update-form" method="POST" enctype="multipart/form-data">{% csrf_token %}

  {{ form }}

  <p>
    {% if object %}
    <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
    {% else %}
    <a href="{% url 'google_workspace:connections' %}" class="btn btn-outline-secondary">Cancel</a>
    {% endif %}
    <button class="btn btn-primary">Save</button>
  </p>
</form>
{% endblock %}

{% block extrajs %}
<script nonce="{{ request.csp_nonce }}">
  function setEnabled(id, enabled) {
    const el = document.getElementById(id);
    if (!el) return;

    el.disabled = !enabled;
  }

  function toggleByType() {
    const typeEl = document.getElementById("id_type");
    if (!typeEl) return;

    const t = typeEl.value;

    const usesClientId = (t === "SA_CLOUD_ID");
    const usesFile     = (t === "OAUTH");

    setEnabled("id_customer_id", usesClientId);
    setEnabled("id_serialized_client_config", usesFile);

    if (usesClientId) {
      const f = document.getElementById("id_serialized_client_config");
      if (f) f.value = "";
    }
    if (usesFile) {
      const c = document.getElementById("id_customer_id");
      if (c) c.value = "";
    }
  }

  document.addEventListener("DOMContentLoaded", () => {
    const typeEl = document.getElementById("id_type");
    if (typeEl) typeEl.addEventListener("change", toggleByType);
    toggleByType(); // initial
  });
</script>
{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/connection_list.html
{% extends 'base.html' %}
{% load ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item active">Connections</li>
</ol>

<div class="d-flex align-items-center mb-1">
    <h2 class="m-0">Connection{{ object_list|length|pluralize }} ({{ object_list|length }})</h2>
    <div class="ms-auto">
        {% if perms.google_workspace.add_connection %}
            {% url 'google_workspace:create_connection' as url %}
            {% button 'CREATE' url "Create connection" %}
        {% endif %}
    </div>
</div>

{% if object_list %}
    <table class="table table-striped align-middle table-hover">
        <thead>
            <tr>
            <th>Name</th>
            {% if perms.google_workspace.change_connection or perms.google_workspace.delete_connection %}
            <th></th>
            {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for connection in object_list %}
            <tr class="data-row">
            <td><a href="{{ connection.get_absolute_url }}">{{ connection }}</a></td>
            {% if perms.google_workspace.change_connection or perms.google_workspace.delete_connection%}
            <td class="text-end py-0">
                {% if perms.google_workspace.change_connection%}
                    {% url 'google_workspace:update_connection' connection.pk as url %}
                    {% button 'UPDATE' url "Edit connection" %}
                {% endif %}
           
                {% if perms.google_workspace.delete_connection%}
                    {% if connection.can_be_deleted %}
                        {% url 'google_workspace:delete_connection' connection.pk as url %}
                        {% button 'DELETE' url "Delete connection" %}
                    {% endif %}
                {% endif %}
            </td>
            {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    {% if perms.google_workspace.add_connection %}
        {% url 'google_workspace:create_connection' as link %}
        {% no_entities 'connections' link %}
    {% else %}
        {% no_entities 'connections' %}
    {% endif %}        
{% endif %}

{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/grouptagmapping_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:connections" %}">Connections</a></li>
  <li class="breadcrumb-item active"><a href="{{ connection.get_absolute_url }}">{{ object.connection }}</a></li>
  <li class="breadcrumb-item active">Remove group tag mapping</li>
</ol>

<h2>Remove group tag mapping</h2>

<form method="post" class="update-form">{% csrf_token %}
  <p>Do you really want to remove group tag mapping <i>{{ object.group_email }}</i> from the connection <i>{{ object.connection }}</i>?</p>
  <p>
    <a class="btn btn-outline-secondary" href="{{ object.get_absolute_url }}">Cancel</a>
    <button class="btn btn-danger" type="submit">Remove</button>
  </p>
</form>
{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/grouptagmapping_form.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:index" %}">Google Workspace</a></li>
  <li class="breadcrumb-item"><a href="{% url "google_workspace:connections" %}">Connections</a></li>
  <li class="breadcrumb-item active"><a href="{{ connection.get_absolute_url }}">{{ connection }}</a></li>
  {% if object %}
  <li class="breadcrumb-item active">Update group tag mapping</li>
  {% else %}
  <li class="breadcrumb-item active">Add group tag mapping</li>
  {% endif %}
</ol>

<h2>{% if object %}Update{% else %}Add{% endif %} group tag mapping</h2>

<form method="post" class="update-form">{% csrf_token %}
  {{ form }}
  <p>
    <a class="btn btn-outline-secondary" href="{{ connection.get_absolute_url }}">
      Cancel
    </a>
    <button class="btn btn-primary" type="submit">Save</button>
  </p>
</form>
{% endblock %}

zentral/contrib/google_workspace/templates/google_workspace/index.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item active">Google Workspace</li>
</ol>

<div class="row">
  <div class="col-md-12">
    <h2>Google Workspace</h2>
  </div>
</div>
{% endblock %}