zentral/contrib/jamf/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = "jamf"
urlpatterns = [

    # index
    path('', views.IndexView.as_view(), name="index"),

    # setup > jamf instances
    path('instances/', views.JamfInstancesView.as_view(), name="jamf_instances"),
    path('instances/create/', views.CreateJamfInstanceView.as_view(), name="create_jamf_instance"),
    path('instances/<int:pk>/', views.JamfInstanceView.as_view(), name="jamf_instance"),
    path('instances/<int:pk>/setup/', views.SetupJamfInstanceView.as_view(), name="setup_jamf_instance"),
    path('instances/<int:pk>/update/', views.UpdateJamfInstanceView.as_view(), name="update_jamf_instance"),
    path('instances/<int:pk>/delete/', views.DeleteJamfInstanceView.as_view(), name="delete_jamf_instance"),
    path('instances/<int:pk>/tag_configs/create/',
         views.CreateTagConfigView.as_view(),
         name="create_tag_config"),
    path('instances/<int:ji_pk>/tag_configs/<int:pk>/update/',
         views.UpdateTagConfigView.as_view(),
         name="update_tag_config"),
    path('instances/<int:ji_pk>/tag_configs/<int:pk>/delete/',
         views.DeleteTagConfigView.as_view(),
         name="delete_tag_config"),
    # API
    path('post_event/<slug:secret>/', csrf_exempt(views.PostEventView.as_view()), name='post_event'),
]


modules_menu_cfg = {
    'items': (
        ('index', 'Overview', False, ('jamf',)),
        ('jamf_instances', 'Instances', False, ('jamf.view_jamfinstance',)),
    ),
    'weight': 60,
}

zentral/contrib/jamf/models.py
import logging
import os.path
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import F
from django.urls import reverse
from django.utils.crypto import get_random_string
from zentral.core.secret_engines import decrypt_str, encrypt_str, rewrap


logger = logging.getLogger("zentral.contrib.jamf.models")


def make_secret():
    return get_random_string(67)


class JamfInstance(models.Model):
    version = models.PositiveIntegerField(editable=False)
    business_unit = models.ForeignKey("inventory.BusinessUnit", on_delete=models.PROTECT, blank=True, null=True)
    host = models.CharField(max_length=256,
                            help_text="host name of the server")
    port = models.IntegerField(validators=[MinValueValidator(1),
                                           MaxValueValidator(65535)],
                               default=8443,
                               help_text="server port number")
    path = models.CharField(max_length=64, default="/JSSResource",
                            help_text="path of the server API")
    user = models.CharField(max_length=64,
                            help_text="API user name")
    password = models.TextField(help_text="API user password", editable=False)
    secret = models.CharField(max_length=256, editable=False, unique=True,
                              default=make_secret)
    bearer_token_authentication = models.BooleanField(default=False)
    inventory_apps_shard = models.IntegerField(
        validators=[MinValueValidator(0),
                    MaxValueValidator(100)],
        default=100
    )
    inventory_extension_attributes = ArrayField(
        models.CharField(max_length=256, validators=[MinLengthValidator(1)]),
        blank=True,
        default=list,
        help_text="Comma separated list of the extension attributes to collect as inventory extra facts"
    )
    principal_user_uid_extension_attribute = models.CharField(
        verbose_name="Principal user UID extension attribute",
        max_length=256,
        blank=True,
        null=True,
        help_text="Extension attribute to use as principal user unique ID"
    )
    principal_user_pn_extension_attribute = models.CharField(
        verbose_name="Principal user principal name extension attribute",
        max_length=256,
        blank=True,
        null=True,
        help_text="Extension attribute to use as principal user principal name"
    )
    principal_user_dn_extension_attribute = models.CharField(
        verbose_name="Principal user display name extension attribute",
        max_length=256,
        blank=True,
        null=True,
        help_text="Extension attribute to use as principal user display name"
    )
    checkin_heartbeat_timeout = models.IntegerField(
        validators=[MinValueValidator(600),
                    MaxValueValidator(172800)],
        default=1200,
        help_text="in seconds, 600 (10 min) → 172800 (2 days)"
    )
    inventory_completed_heartbeat_timeout = models.IntegerField(
        validators=[MinValueValidator(600),
                    MaxValueValidator(604800)],
        default=172800,
        help_text="in seconds, 600 (10 min) → 604800 (7 days)"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('host', 'port', 'path')

    def __str__(self):
        return self.host

    def get_absolute_url(self):
        return reverse("jamf:jamf_instance", args=(self.pk,))

    def save(self, *args, **kwargs):
        if not self.id:
            self.version = 0
        elif kwargs.pop("bump_version", True):
            self.version = F("version") + 1
        super().save(*args, **kwargs)

    def base_url(self):
        return "https://{}:{}".format(self.host, self.port)

    def api_base_url(self):
        return "{}{}".format(self.base_url(), self.path)

    def api_doc_url(self):
        return "{}{}".format(self.base_url(), os.path.join(self.path, "../api"))

    def serialize(self, decrypt_password=False):
        d = {
            "pk": self.pk,
            "version": self.version,
            "host": self.host,
            "port": self.port,
            "path": self.path,
            "user": self.user,
            "password": self.get_password() if decrypt_password else self.password,
            "bearer_token_authentication": self.bearer_token_authentication,
            "secret": self.secret,
            "inventory_apps_shard": self.inventory_apps_shard,
            "inventory_extension_attributes": self.inventory_extension_attributes,
            "principal_user_uid_extension_attribute": self.principal_user_uid_extension_attribute,
            "principal_user_pn_extension_attribute": self.principal_user_pn_extension_attribute,
            "principal_user_dn_extension_attribute": self.principal_user_dn_extension_attribute,
            "tag_configs": [tm.serialize() for tm in self.tagconfig_set.select_related("taxonomy").all()],
        }
        if self.business_unit:
            d["business_unit"] = self.business_unit.serialize()
        return d

    def observer_dict(self):
        return {"hostname": self.host,
                "vendor": "Jamf",
                "product": "Jamf Pro",
                "type": "MDM",
                "content_type": "jamf.jamfinstance",
                "pk": self.pk}

    # secrets

    def get_password(self):
        if not self.pk:
            raise ValueError("JamfInstance must have a PK")
        return decrypt_str(self.password, field="password", model="jamf.jamfinstance", pk=self.pk)

    def set_password(self, password):
        if not self.pk:
            raise ValueError("JamfInstance must have a PK")
        self.password = encrypt_str(password, field="password", model="jamf.jamfinstance", pk=self.pk)

    def rewrap_secrets(self):
        if not self.pk:
            raise ValueError("JamfInstance must have a PK")
        self.password = rewrap(self.password, field="password", model="jamf.jamfinstance", pk=self.pk)


class TagConfig(models.Model):
    GROUP_SOURCE = "GROUP"
    SOURCE_CHOICES = (
        (GROUP_SOURCE, "Group"),
    )
    instance = models.ForeignKey(JamfInstance, on_delete=models.CASCADE)
    source = models.CharField(max_length=16, choices=SOURCE_CHOICES, default=GROUP_SOURCE)
    taxonomy = models.ForeignKey("inventory.Taxonomy", on_delete=models.CASCADE)
    regex = models.CharField(
        max_length=256,
        help_text="matching names will be used to automatically generate tags"
    )
    replacement = models.CharField(
        max_length=32,
        help_text="replacement pattern used to generate a tag name from a tag regex match"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return "{}#tag-config-{}".format(self.instance.get_absolute_url(), self.pk)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.instance.save()

    def serialize(self):
        return {"source": self.source,
                "taxonomy_id": self.taxonomy.id,
                "regex": self.regex,
                "replacement": self.replacement}

zentral/contrib/jamf/templates/jamf/index.html
{% extends 'base.html' %}
{% load ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item active">Jamf</li>
</ol>

<div class="row">
  <div class="col-md-12">
    <h2>Jamf</h2>
  </div>
  <div class="col-sm-6">
    <canvas class="chart"
            data-app="jamf"
            data-dataset="event_count"
            width="200"
            height="120"></canvas>
  </div>
  <div class="col-sm-6">
    <canvas class="chart"
            data-app="jamf"
            data-dataset="unique_msn"
            width="200"
            height="120"></canvas>
  </div>
  <div class="col-md-12">
    {% if perms.jamf.view_jamfinstance %}
        <div class="d-flex align-items-center mb-1">
            <h3>Instance{{ instances_count|pluralize }} ({{ instances_count }})</h3>
            <div class="ms-auto">
                {% if perms.jamf.add_jamfinstance %}
                    {% url 'jamf:create_jamf_instance' as url %}
                    {% button 'CREATE' url "Create new Instance" %}
                {% endif %}
            </div>
        </div>
        {% if instances %}
        <table class="table table-striped align-middle table-hover">
            <thead>
                <tr>
                <th>Host</th>
                <th>API User</th>
                <th>Business unit</th>
                {% if perms.jamf.change_jamfinstance %}
                <th></th>
                {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for jamf_instance in instances %}
                <tr class="data-row">
                <td><a href="{{ jamf_instance.get_absolute_url }}">{{ jamf_instance.host }}</a></td>
                <td>{{ jamf_instance.user }}</td>
                <td>
                    {% if jamf_instance.business_unit %}
                    {{ jamf_instance.business_unit }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                {% if perms.jamf.change_jamfinstance %}
                <td class="text-end py-0">
                    {% url 'jamf:update_jamf_instance' jamf_instance.pk as url %}
                    {% button 'UPDATE' url "Edit Instance" %}
                </td>
                {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            {% if perms.jamf.add_jamfinstance %}
                {% url 'jamf:create_jamf_instance' as link %}
                {% no_entities 'Instances' link %}
            {% else %}
                {% no_entities 'Instances' %}
            {% endif %}
        {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script nonce="{{ request.csp_nonce }}">
  function get_data_and_make_chart(url, charts) {
    $.getJSON(url, function(data) {
      for (var dataset in data.datasets) {
        if (data.datasets.hasOwnProperty(dataset)) {
          var canvas = charts[data.app][dataset];
          var chart = new Chart(canvas, {
            type: 'bar',
            data: {labels: data.labels,
                   datasets: [data.datasets[dataset]]},
            options: {
                scales: {
                    x: {gridLines: { color: "darkgray", zeroLineColor: "darkgray" }},
                    y: {gridLines: { color: "darkgray", zeroLineColor: "darkgray" }}
                }
            }
          });
        }
      }
    });
  }

  $(document).ready(function(){
    var charts = {};
    var urls = Array();
    $(".chart").each(function(index, canvas) {
      canvas = $(canvas);
      var app = canvas.data('app');
      var dataset = canvas.data('dataset');
      if(! charts.hasOwnProperty(app)) {
        charts[app] = {};
        urls.push('/app/' + app + '/hist_data/day/14/');
      }
      charts[app][dataset] = canvas;
    });
    for (var idx in urls) {
      if (urls.hasOwnProperty(idx)) {
        get_data_and_make_chart(urls[idx], charts);
      }
    }
  });
</script>
{% endblock %}

zentral/contrib/jamf/templates/jamf/jamfinstance_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item"><a href="{% url 'jamf:jamf_instances' %}">Instances</a></li>
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="breadcrumb-item active">Delete</li>
</ol>

<h2>{{ title }}</h2>

<form method="POST">{% csrf_token %}
  <p>Do you really want to delete this instance ?</p>
  <p>
    <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
    <button class="btn btn-danger">Delete</button>
  </p>
</form>

{% endblock %}

zentral/contrib/jamf/templates/jamf/jamfinstance_detail.html
{% extends 'base.html' %}
{% load base_extras %}
{% load ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item"><a href="{% url 'jamf:jamf_instances' %}">Instances</a></li>
  <li class="breadcrumb-item active">{{ object }}</li>
</ol>

<div class="object-details">
    <div class="d-flex align-items-center mb-1">
        <h2 class="m-0">{{ title }}</h2>
    </div>
    <div class="d-flex align-items-center mb-3">
        <h3 class="m-0 fs-5 text-secondary">Instance</h3>
        <div class="ms-auto">
            {% url 'jamf:delete_jamf_instance' object.pk as url %}
            {% button 'LINK' object.api_doc_url "API resource documentation" %}

            {% if perms.jamf.change_jamfinstance %}
            <a href="{% url 'jamf:setup_jamf_instance' object.pk %}" class="btn btn-link"
                data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Setup webhooks">
                <i class="bi bi-arrow-left-right"></i>
            </a>
                {% url 'jamf:update_jamf_instance' object.pk as url %}
                {% button 'UPDATE' url "Edit Instance" %}
            {% endif %}
            {% if perms.jamf.delete_jamfinstance %}
                {% url 'jamf:delete_jamf_instance' object.pk as url %}
                {% button 'DELETE' url "Delete Instance" %}
            {% endif %}
        </div>
    </div>
    
    <table class="table-object-properties">
    <thead>
        <tr>
        <th style="width:30vw">Attribute</th>
        <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td>Business unit</td>
        <td>
            {% if object.business_unit %}
            <a href="{% url 'inventory:mbu_machines' object.business_unit.meta_business_unit.id %}">
            {{ object.business_unit }}
            </a>
            {% else %}
            -
            {% endif %}
        </td>
        </tr>
        <tr>
        <td>API URL</td>
        <td>{{ object.api_base_url }}</td>
        </tr>
        <tr>
        <td>API user</td>
        <td>{{ object.user }}</td>
        </tr>
        <tr>
        <td>Use Bearer token authentication</td>
        <td>{{ object.bearer_token_authentication|yesno }}</td>
        </tr>
        <tr>
        <td>Inventory apps shard</td>
        <td>{{ object.inventory_apps_shard }}%</td>
        </tr>
        <tr>
        <td>Inventory extension attribute{{ object.inventory_extension_attributes|length|pluralize }}</td>
        <td>{{ object.inventory_extension_attributes|join:", "|default:"-" }}</td>
        </tr>
        <tr>
        <td>Principal user UID extension attribute</td>
        <td>{{ object.principal_user_uid_extension_attribute|default:"-" }}</td>
        </tr>
        <tr>
        <td>Principal user principal name extension attribute</td>
        <td>{{ object.principal_user_pn_extension_attribute|default:"-" }}</td>
        </tr>
        <tr>
        <td>Principal user display name extension attribute</td>
        <td>{{ object.principal_user_dn_extension_attribute|default:"-" }}</td>
        </tr>
        <tr>
        <td>Check-in heartbeat timeout</td>
        <td>{{ object.checkin_heartbeat_timeout|duration_repr }}</td>
        </tr>
        <tr>
        <td>Inventory completed heartbeat timeout</td>
        <td>{{ object.inventory_completed_heartbeat_timeout|duration_repr }}</td>
        </tr>
    </tbody>
    </table>
</div>

{% created_updated_at object %}

{% if perms.jamf.view_tagconfig %}
<div class="d-flex justify-content-between mb-3">
    <h3>Tag config{{  tag_config_count|pluralize }} ({{ tag_config_count }})</h3>
    <div class="ms-auto">            
        {% if perms.jamf.add_tagconfig %}
            {% url 'jamf:create_tag_config' object.pk as url %}
            {% button 'CREATE' url "Add new Tag Config" %}
        {% endif %}
    </div>
</div>

{% if tag_configs %}
<div class="table-responsive mb-3">
    <table class="table table-striped align-middle table-hover">
    <thead>
        <tr>
        <th>Source</th>
        <th>Taxonomy</th>
        <th>Regex</th>
        <th>Replacement</th>
        {% if perms.jamf.change_tagconfig or perms.jamf.delete_tagconfig %}
        <th></th>
        {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for tag_config in tag_configs %}
        <tr id="tag-config-{{ tag_config.pk }}" class="data-row">
        <td>{{ tag_config.get_source_display }}</td>
        <td>{{ tag_config.taxonomy }}</td>
        <td>{{ tag_config.regex }}</td>
        <td>{{ tag_config.replacement }}</td>
        {% if perms.jamf.change_tagconfig or perms.jamf.delete_tagconfig %}
        <td class="text-end py-0">
            {% if perms.jamf.change_tagconfig %}
                {% url 'jamf:update_tag_config' object.pk tag_config.pk  as url %}
                {% button 'UPDATE' url "Edit Tag Configuration" %}
            {% endif %}
            {% if perms.jamf.delete_tagconfig %}
                {% url 'jamf:delete_tag_config' object.pk tag_config.pk as url %}
                {% button 'DELETE' url "Delete Tag Configuration" %}
            {% endif %}
        </td>
        {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    </table>
    {% endif %}
</div>
{% endif %}
{% endblock %}

zentral/contrib/jamf/templates/jamf/jamfinstance_form.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item"><a href="{% url 'jamf:jamf_instances' %}">Instances</a></li>
  {% if object %}
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="breadcrumb-item active">Update</li>
  {% else %}
  <li class="breadcrumb-item active">Create</li>
  {% endif %}
</ol>

<h2>{{ title }}</h2>

<form method="POST" class="update-form">{% csrf_token %}

  {{ form }}

  <p>
    {% if object %}
    <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
    {% else %}
    <a href="{% url 'jamf:jamf_instances' %}" class="btn btn-outline-secondary">Cancel</a>
    {% endif %}
    <button class="btn btn-primary">Save</button>
  </p>
</form>
{% endblock %}

zentral/contrib/jamf/templates/jamf/jamfinstance_list.html
{% extends 'base.html' %}
{% load ui_extras %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item active">Instances</li>
</ol>

<div class="d-flex align-items-center mb-1">
    <h2 class="m-0">Instance{{ jamf_instances_count|pluralize }} ({{ jamf_instances_count }})</h2>
    <div class="ms-auto">
        {% if perms.jamf.add_jamfinstance %}
            {% url 'jamf:create_jamf_instance' as url %}
            {% button 'CREATE' url "Create new Instance" %}
        {% endif %}
    </div>
</div>

{% if object_list %}
    <table class="table table-striped align-middle table-hover">
        <thead>
            <tr>
            <th>Host</th>
            <th>API User</th>
            <th>Business unit</th>
            {% if perms.jamf.change_jamfinstance %}
            <th></th>
            {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for jamf_instance in object_list %}
            <tr class="data-row">
            <td><a href="{{ jamf_instance.get_absolute_url }}">{{ jamf_instance.host }}</a></td>
            <td>{{ jamf_instance.user }}</td>
            <td>
                {% if jamf_instance.business_unit %}
                {{ jamf_instance.business_unit }}
                {% else %}
                -
                {% endif %}
            </td>
            {% if perms.jamf.change_jamfinstance %}
            <td class="text-end py-0">
                {% url 'jamf:update_jamf_instance' jamf_instance.pk as url %}
                {% button 'UPDATE' url "Edit Instance" %}
            </td>
            {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    {% if perms.jamf.add_jamfinstance %}
        {% url 'jamf:create_jamf_instance' as link %}
        {% no_entities 'Jamf instances' link %}
    {% else %}
        {% no_entities 'Jamf instances' %}
    {% endif %}        
{% endif %}

{% endblock %}

zentral/contrib/jamf/templates/jamf/tagconfig_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item"><a href="{% url 'jamf:jamf_instances' %}">Instances</a></li>
  <li class="breadcrumb-item"><a href="{{ jamf_instance.get_absolute_url }}">{{ jamf_instance }}</a></li>
  <li class="breadcrumb-item active">{{ title }}</li>
</ol>

<h2>{{ title }}</h2>

<form method="POST">{% csrf_token %}
  <p>Do you really want to delete this tag config ?</p>
  <p>
    <a href="{{ jamf_instance.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
    <button class="btn btn-danger">Delete</button>
  </p>
</form>

{% endblock %}

zentral/contrib/jamf/templates/jamf/tagconfig_form.html
{% extends 'base.html' %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url "jamf:index" %}">Jamf</a></li>
  <li class="breadcrumb-item"><a href="{% url 'jamf:jamf_instances' %}">Instances</a></li>
  <li class="breadcrumb-item"><a href="{{ jamf_instance.get_absolute_url }}">{{ jamf_instance }}</a></li>
  <li class="breadcrumb-item active">{{ title }}</li>
</ol>

<h2>{{ title }}</h2>

<form method="POST" class="update-form">{% csrf_token %}
  {{ form }}
  <p>
    <a href="{{ jamf_instance.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
    <button class="btn btn-primary">Save</button>
  </p>
</form>
{% endblock %}